/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";

// export const jsonSchema = z.lazy(() =>
// 	z
// 		.union([
// 			z.string(),
// 			z.number(),
// 			z.boolean(),
// 			z.record(z.string(), z.union([jsonSchema, z.undefined()])),
// 			z.array(jsonSchema),
// 		])
// 		.nullable(),
// );

export const jsonSchema: z.ZodType<any> = z.lazy(() =>
	z
		.union([
			z.string(),
			z.number(),
			z.boolean(),
			z.record(z.string(), z.union([jsonSchema, z.undefined()])),
			z.array(jsonSchema),
		])
		.nullable(),
);

export const publicAirCompaniesRowSchema = z.object({
	address: z.string().nullable(),
	ceo_name: z.string().nullable(),
	city: z.string().nullable(),
	clients_count: z.number().nullable(),
	competitors: z.string().nullable(),
	core_values: z.string().nullable(),
	created_at: z.string().nullable(),
	description: z.string(),
	email: z.string().nullable(),
	employees_count: z.number().nullable(),
	id: z.string(),
	industry: z.string(),
	inn: z.string().nullable(),
	key_processes: z.string().nullable(),
	legal_form: z.string().nullable(),
	main_problems: z.string().nullable(),
	mission: z.string().nullable(),
	name: z.string(),
	ogrn: z.string().nullable(),
	onboarding_completed: z.boolean().nullable(),
	owner_tg_id: z.number(),
	phone: z.string().nullable(),
	products_services: z.string().nullable(),
	revenue_monthly: z.number().nullable(),
	swot_opportunities: z.string().nullable(),
	swot_strengths: z.string().nullable(),
	swot_threats: z.string().nullable(),
	swot_weaknesses: z.string().nullable(),
	updated_at: z.string().nullable(),
	used_systems: z.string().nullable(),
	website: z.string().nullable(),
});

export const publicAirCompaniesInsertSchema = z.object({
	address: z.string().optional().nullable(),
	ceo_name: z.string().optional().nullable(),
	city: z.string().optional().nullable(),
	clients_count: z.number().optional().nullable(),
	competitors: z.string().optional().nullable(),
	core_values: z.string().optional().nullable(),
	created_at: z.string().optional().nullable(),
	description: z.string(),
	email: z.string().optional().nullable(),
	employees_count: z.number().optional().nullable(),
	id: z.string().optional(),
	industry: z.string(),
	inn: z.string().optional().nullable(),
	key_processes: z.string().optional().nullable(),
	legal_form: z.string().optional().nullable(),
	main_problems: z.string().optional().nullable(),
	mission: z.string().optional().nullable(),
	name: z.string(),
	ogrn: z.string().optional().nullable(),
	onboarding_completed: z.boolean().optional().nullable(),
	owner_tg_id: z.number(),
	phone: z.string().optional().nullable(),
	products_services: z.string().optional().nullable(),
	revenue_monthly: z.number().optional().nullable(),
	swot_opportunities: z.string().optional().nullable(),
	swot_strengths: z.string().optional().nullable(),
	swot_threats: z.string().optional().nullable(),
	swot_weaknesses: z.string().optional().nullable(),
	updated_at: z.string().optional().nullable(),
	used_systems: z.string().optional().nullable(),
	website: z.string().optional().nullable(),
});

export const publicAirCompaniesUpdateSchema = z.object({
	address: z.string().optional().nullable(),
	ceo_name: z.string().optional().nullable(),
	city: z.string().optional().nullable(),
	clients_count: z.number().optional().nullable(),
	competitors: z.string().optional().nullable(),
	core_values: z.string().optional().nullable(),
	created_at: z.string().optional().nullable(),
	description: z.string().optional(),
	email: z.string().optional().nullable(),
	employees_count: z.number().optional().nullable(),
	id: z.string().optional(),
	industry: z.string().optional(),
	inn: z.string().optional().nullable(),
	key_processes: z.string().optional().nullable(),
	legal_form: z.string().optional().nullable(),
	main_problems: z.string().optional().nullable(),
	mission: z.string().optional().nullable(),
	name: z.string().optional(),
	ogrn: z.string().optional().nullable(),
	onboarding_completed: z.boolean().optional().nullable(),
	owner_tg_id: z.number().optional(),
	phone: z.string().optional().nullable(),
	products_services: z.string().optional().nullable(),
	revenue_monthly: z.number().optional().nullable(),
	swot_opportunities: z.string().optional().nullable(),
	swot_strengths: z.string().optional().nullable(),
	swot_threats: z.string().optional().nullable(),
	swot_weaknesses: z.string().optional().nullable(),
	updated_at: z.string().optional().nullable(),
	used_systems: z.string().optional().nullable(),
	website: z.string().optional().nullable(),
});

export const publicAirDepartmentsRowSchema = z.object({
	created_at: z.string().nullable(),
	description: z.string().nullable(),
	id: z.number(),
	name: z.string(),
});

export const publicAirDepartmentsInsertSchema = z.object({
	created_at: z.string().optional().nullable(),
	description: z.string().optional().nullable(),
	id: z.number().optional(),
	name: z.string(),
});

export const publicAirDepartmentsUpdateSchema = z.object({
	created_at: z.string().optional().nullable(),
	description: z.string().optional().nullable(),
	id: z.number().optional(),
	name: z.string().optional(),
});

export const publicAirDocumentTemplatesRowSchema = z.object({
	created_at: z.string().nullable(),
	default_format: z.string().nullable(),
	description: z.string().nullable(),
	document_type: z.string(),
	id: z.string(),
	is_active: z.boolean().nullable(),
	name: z.string(),
	required_fields: jsonSchema.nullable(),
	template_content: z.string(),
	updated_at: z.string().nullable(),
});

export const publicAirDocumentTemplatesInsertSchema = z.object({
	created_at: z.string().optional().nullable(),
	default_format: z.string().optional().nullable(),
	description: z.string().optional().nullable(),
	document_type: z.string(),
	id: z.string().optional(),
	is_active: z.boolean().optional().nullable(),
	name: z.string(),
	required_fields: jsonSchema.optional().nullable(),
	template_content: z.string(),
	updated_at: z.string().optional().nullable(),
});

export const publicAirDocumentTemplatesUpdateSchema = z.object({
	created_at: z.string().optional().nullable(),
	default_format: z.string().optional().nullable(),
	description: z.string().optional().nullable(),
	document_type: z.string().optional(),
	id: z.string().optional(),
	is_active: z.boolean().optional().nullable(),
	name: z.string().optional(),
	required_fields: jsonSchema.optional().nullable(),
	template_content: z.string().optional(),
	updated_at: z.string().optional().nullable(),
});

export const publicAirDocumentsRowSchema = z.object({
	chunks_count: z.number().nullable(),
	created_at: z.string().nullable(),
	department_id: z.number().nullable(),
	file_id: z.string().nullable(),
	file_name: z.string(),
	file_size: z.number().nullable(),
	id: z.string(),
	s3_url: z.string().nullable(),
	user_id: z.number(),
});

export const publicAirDocumentsInsertSchema = z.object({
	chunks_count: z.number().optional().nullable(),
	created_at: z.string().optional().nullable(),
	department_id: z.number().optional().nullable(),
	file_id: z.string().optional().nullable(),
	file_name: z.string(),
	file_size: z.number().optional().nullable(),
	id: z.string().optional(),
	s3_url: z.string().optional().nullable(),
	user_id: z.number(),
});

export const publicAirDocumentsUpdateSchema = z.object({
	chunks_count: z.number().optional().nullable(),
	created_at: z.string().optional().nullable(),
	department_id: z.number().optional().nullable(),
	file_id: z.string().optional().nullable(),
	file_name: z.string().optional(),
	file_size: z.number().optional().nullable(),
	id: z.string().optional(),
	s3_url: z.string().optional().nullable(),
	user_id: z.number().optional(),
});

export const publicAirDocumentsRelationshipsSchema = z.tuple([
	z.object({
		foreignKeyName: z.literal("air_documents_department_id_fkey"),
		columns: z.tuple([z.literal("department_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("air_departments"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("air_documents_user_id_fkey"),
		columns: z.tuple([z.literal("user_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("air_profiles"),
		referencedColumns: z.tuple([z.literal("tg_id")]),
	}),
]);

export const publicAirFavoritesRowSchema = z.object({
	chat_id: z.number(),
	created_at: z.string().nullable(),
	id: z.string(),
	message_id: z.number(),
	message_text: z.string().nullable(),
	message_type: z.string().nullable(),
	user_id: z.number(),
});

export const publicAirFavoritesInsertSchema = z.object({
	chat_id: z.number(),
	created_at: z.string().optional().nullable(),
	id: z.string().optional(),
	message_id: z.number(),
	message_text: z.string().optional().nullable(),
	message_type: z.string().optional().nullable(),
	user_id: z.number(),
});

export const publicAirFavoritesUpdateSchema = z.object({
	chat_id: z.number().optional(),
	created_at: z.string().optional().nullable(),
	id: z.string().optional(),
	message_id: z.number().optional(),
	message_text: z.string().optional().nullable(),
	message_type: z.string().optional().nullable(),
	user_id: z.number().optional(),
});

export const publicAirGeneratedDocumentsRowSchema = z.object({
	celery_task_id: z.string().nullable(),
	completed_at: z.string().nullable(),
	created_at: z.string().nullable(),
	document_type: z.string(),
	error_message: z.string().nullable(),
	file_format: z.string(),
	file_name: z.string(),
	file_size_bytes: z.number().nullable(),
	id: z.string(),
	is_favorite: z.boolean().nullable(),
	is_vectorized: z.boolean().nullable(),
	metadata: jsonSchema.nullable(),
	s3_path: z.string(),
	s3_url: z.string().nullable(),
	status: z.string().nullable(),
	template_name: z.string().nullable(),
	user_id: z.number(),
});

export const publicAirGeneratedDocumentsInsertSchema = z.object({
	celery_task_id: z.string().optional().nullable(),
	completed_at: z.string().optional().nullable(),
	created_at: z.string().optional().nullable(),
	document_type: z.string(),
	error_message: z.string().optional().nullable(),
	file_format: z.string(),
	file_name: z.string(),
	file_size_bytes: z.number().optional().nullable(),
	id: z.string().optional(),
	is_favorite: z.boolean().optional().nullable(),
	is_vectorized: z.boolean().optional().nullable(),
	metadata: jsonSchema.optional().nullable(),
	s3_path: z.string(),
	s3_url: z.string().optional().nullable(),
	status: z.string().optional().nullable(),
	template_name: z.string().optional().nullable(),
	user_id: z.number(),
});

export const publicAirGeneratedDocumentsUpdateSchema = z.object({
	celery_task_id: z.string().optional().nullable(),
	completed_at: z.string().optional().nullable(),
	created_at: z.string().optional().nullable(),
	document_type: z.string().optional(),
	error_message: z.string().optional().nullable(),
	file_format: z.string().optional(),
	file_name: z.string().optional(),
	file_size_bytes: z.number().optional().nullable(),
	id: z.string().optional(),
	is_favorite: z.boolean().optional().nullable(),
	is_vectorized: z.boolean().optional().nullable(),
	metadata: jsonSchema.optional().nullable(),
	s3_path: z.string().optional(),
	s3_url: z.string().optional().nullable(),
	status: z.string().optional().nullable(),
	template_name: z.string().optional().nullable(),
	user_id: z.number().optional(),
});

export const publicAirProfilesRowSchema = z.object({
	communication_style: z.string().nullable(),
	created_at: z.string().nullable(),
	department_id: z.number().nullable(),
	full_name: z.string().nullable(),
	id: z.string(),
	role: z.string(),
	search_mode: z.string().nullable(),
	tg_id: z.number(),
	tone: z.string().nullable(),
	updated_at: z.string().nullable(),
	username: z.string().nullable(),
});

export const publicAirProfilesInsertSchema = z.object({
	communication_style: z.string().optional().nullable(),
	created_at: z.string().optional().nullable(),
	department_id: z.number().optional().nullable(),
	full_name: z.string().optional().nullable(),
	id: z.string().optional(),
	role: z.string().optional(),
	search_mode: z.string().optional().nullable(),
	tg_id: z.number(),
	tone: z.string().optional().nullable(),
	updated_at: z.string().optional().nullable(),
	username: z.string().optional().nullable(),
});

export const publicAirProfilesUpdateSchema = z.object({
	communication_style: z.string().optional().nullable(),
	created_at: z.string().optional().nullable(),
	department_id: z.number().optional().nullable(),
	full_name: z.string().optional().nullable(),
	id: z.string().optional(),
	role: z.string().optional(),
	search_mode: z.string().optional().nullable(),
	tg_id: z.number().optional(),
	tone: z.string().optional().nullable(),
	updated_at: z.string().optional().nullable(),
	username: z.string().optional().nullable(),
});

export const publicAirProfilesRelationshipsSchema = z.tuple([
	z.object({
		foreignKeyName: z.literal("air_profiles_department_id_fkey"),
		columns: z.tuple([z.literal("department_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("air_departments"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
]);

export const publicAirRolePromptsRowSchema = z.object({
	id: z.number(),
	is_active: z.boolean().nullable(),
	role_key: z.string(),
	role_name: z.string(),
	system_prompt: z.string(),
	updated_at: z.string(),
});

export const publicAirRolePromptsInsertSchema = z.object({
	id: z.number().optional(),
	is_active: z.boolean().optional().nullable(),
	role_key: z.string(),
	role_name: z.string(),
	system_prompt: z.string(),
	updated_at: z.string().optional(),
});

export const publicAirRolePromptsUpdateSchema = z.object({
	id: z.number().optional(),
	is_active: z.boolean().optional().nullable(),
	role_key: z.string().optional(),
	role_name: z.string().optional(),
	system_prompt: z.string().optional(),
	updated_at: z.string().optional(),
});

export const publicFileEntityLinksRowSchema = z.object({
	entity_id: z.string(),
	entity_type: z.string(),
	file_id: z.string(),
	id: z.string(),
	linked_at: z.string().nullable(),
	linked_by: z.string().nullable(),
	notes: z.string().nullable(),
});

export const publicFileEntityLinksInsertSchema = z.object({
	entity_id: z.string(),
	entity_type: z.string(),
	file_id: z.string(),
	id: z.string().optional(),
	linked_at: z.string().optional().nullable(),
	linked_by: z.string().optional().nullable(),
	notes: z.string().optional().nullable(),
});

export const publicFileEntityLinksUpdateSchema = z.object({
	entity_id: z.string().optional(),
	entity_type: z.string().optional(),
	file_id: z.string().optional(),
	id: z.string().optional(),
	linked_at: z.string().optional().nullable(),
	linked_by: z.string().optional().nullable(),
	notes: z.string().optional().nullable(),
});

export const publicFileEntityLinksRelationshipsSchema = z.tuple([
	z.object({
		foreignKeyName: z.literal("file_entity_links_file_id_fkey"),
		columns: z.tuple([z.literal("file_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("file_entity_links_file_id_fkey"),
		columns: z.tuple([z.literal("file_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files_with_entities"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("file_entity_links_file_id_fkey"),
		columns: z.tuple([z.literal("file_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files_with_item_count"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
]);

export const publicFileVersionsRowSchema = z.object({
	created_at: z.string().nullable(),
	created_by: z.string().nullable(),
	file_id: z.string(),
	id: z.string(),
	mime_type: z.string().nullable(),
	size: z.number(),
	storage_path: z.string(),
	version_number: z.number(),
});

export const publicFileVersionsInsertSchema = z.object({
	created_at: z.string().optional().nullable(),
	created_by: z.string().optional().nullable(),
	file_id: z.string(),
	id: z.string().optional(),
	mime_type: z.string().optional().nullable(),
	size: z.number(),
	storage_path: z.string(),
	version_number: z.number(),
});

export const publicFileVersionsUpdateSchema = z.object({
	created_at: z.string().optional().nullable(),
	created_by: z.string().optional().nullable(),
	file_id: z.string().optional(),
	id: z.string().optional(),
	mime_type: z.string().optional().nullable(),
	size: z.number().optional(),
	storage_path: z.string().optional(),
	version_number: z.number().optional(),
});

export const publicFileVersionsRelationshipsSchema = z.tuple([
	z.object({
		foreignKeyName: z.literal("file_versions_file_id_fkey"),
		columns: z.tuple([z.literal("file_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("file_versions_file_id_fkey"),
		columns: z.tuple([z.literal("file_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files_with_entities"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("file_versions_file_id_fkey"),
		columns: z.tuple([z.literal("file_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files_with_item_count"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
]);

export const publicFilesRowSchema = z.object({
	bucket: z.string(),
	can_delete: z.boolean().nullable(),
	can_index: z.boolean().nullable(),
	can_read: z.boolean().nullable(),
	can_write: z.boolean().nullable(),
	chunks_count: z.number().nullable(),
	created_at: z.string().nullable(),
	created_by: z.string().nullable(),
	embedding_model: z.string().nullable(),
	id: z.string(),
	index_status: z.string().nullable(),
	indexing_error: z.string().nullable(),
	indexing_progress: z.number().nullable(),
	is_folder: z.boolean().nullable(),
	last_indexed: z.string().nullable(),
	mime_type: z.string().nullable(),
	name: z.string(),
	parent_id: z.string().nullable(),
	path: z.string(),
	size: z.number().nullable(),
	sort_order: z.number().nullable(),
	starred: z.boolean().nullable(),
	storage_path: z.string(),
	storage_provider: z.string(),
	tags: z.array(z.string()).nullable(),
	type: z.string(),
	updated_at: z.string().nullable(),
	updated_by: z.string().nullable(),
	vector_id: z.string().nullable(),
});

export const publicFilesInsertSchema = z.object({
	bucket: z.string(),
	can_delete: z.boolean().optional().nullable(),
	can_index: z.boolean().optional().nullable(),
	can_read: z.boolean().optional().nullable(),
	can_write: z.boolean().optional().nullable(),
	chunks_count: z.number().optional().nullable(),
	created_at: z.string().optional().nullable(),
	created_by: z.string().optional().nullable(),
	embedding_model: z.string().optional().nullable(),
	id: z.string().optional(),
	index_status: z.string().optional().nullable(),
	indexing_error: z.string().optional().nullable(),
	indexing_progress: z.number().optional().nullable(),
	is_folder: z.boolean().optional().nullable(),
	last_indexed: z.string().optional().nullable(),
	mime_type: z.string().optional().nullable(),
	name: z.string(),
	parent_id: z.string().optional().nullable(),
	path: z.string(),
	size: z.number().optional().nullable(),
	sort_order: z.number().optional().nullable(),
	starred: z.boolean().optional().nullable(),
	storage_path: z.string(),
	storage_provider: z.string(),
	tags: z.array(z.string()).optional().nullable(),
	type: z.string(),
	updated_at: z.string().optional().nullable(),
	updated_by: z.string().optional().nullable(),
	vector_id: z.string().optional().nullable(),
});

export const publicFilesUpdateSchema = z.object({
	bucket: z.string().optional(),
	can_delete: z.boolean().optional().nullable(),
	can_index: z.boolean().optional().nullable(),
	can_read: z.boolean().optional().nullable(),
	can_write: z.boolean().optional().nullable(),
	chunks_count: z.number().optional().nullable(),
	created_at: z.string().optional().nullable(),
	created_by: z.string().optional().nullable(),
	embedding_model: z.string().optional().nullable(),
	id: z.string().optional(),
	index_status: z.string().optional().nullable(),
	indexing_error: z.string().optional().nullable(),
	indexing_progress: z.number().optional().nullable(),
	is_folder: z.boolean().optional().nullable(),
	last_indexed: z.string().optional().nullable(),
	mime_type: z.string().optional().nullable(),
	name: z.string().optional(),
	parent_id: z.string().optional().nullable(),
	path: z.string().optional(),
	size: z.number().optional().nullable(),
	sort_order: z.number().optional().nullable(),
	starred: z.boolean().optional().nullable(),
	storage_path: z.string().optional(),
	storage_provider: z.string().optional(),
	tags: z.array(z.string()).optional().nullable(),
	type: z.string().optional(),
	updated_at: z.string().optional().nullable(),
	updated_by: z.string().optional().nullable(),
	vector_id: z.string().optional().nullable(),
});

export const publicFilesRelationshipsSchema = z.tuple([
	z.object({
		foreignKeyName: z.literal("files_parent_id_fkey"),
		columns: z.tuple([z.literal("parent_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("files_parent_id_fkey"),
		columns: z.tuple([z.literal("parent_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files_with_entities"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("files_parent_id_fkey"),
		columns: z.tuple([z.literal("parent_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files_with_item_count"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
]);

export const publicInvitesRowSchema = z.object({
	accepted_at: z.string().nullable(),
	accepted_by: z.string().nullable(),
	created_at: z.string(),
	email: z.string(),
	expires_at: z.string(),
	id: z.string(),
	invited_by: z.string(),
	role: z.string().nullable(),
	status: z.string(),
	token: z.string(),
	updated_at: z.string(),
});

export const publicInvitesInsertSchema = z.object({
	accepted_at: z.string().optional().nullable(),
	accepted_by: z.string().optional().nullable(),
	created_at: z.string().optional(),
	email: z.string(),
	expires_at: z.string().optional(),
	id: z.string().optional(),
	invited_by: z.string(),
	role: z.string().optional().nullable(),
	status: z.string().optional(),
	token: z.string(),
	updated_at: z.string().optional(),
});

export const publicInvitesUpdateSchema = z.object({
	accepted_at: z.string().optional().nullable(),
	accepted_by: z.string().optional().nullable(),
	created_at: z.string().optional(),
	email: z.string().optional(),
	expires_at: z.string().optional(),
	id: z.string().optional(),
	invited_by: z.string().optional(),
	role: z.string().optional().nullable(),
	status: z.string().optional(),
	token: z.string().optional(),
	updated_at: z.string().optional(),
});

export const publicProfilesRowSchema = z.object({
	avatar_url: z.string().nullable(),
	created_at: z.string(),
	email: z.string(),
	full_name: z.string().nullable(),
	id: z.string(),
	last_seen_at: z.string().nullable(),
	updated_at: z.string(),
});

export const publicProfilesInsertSchema = z.object({
	avatar_url: z.string().optional().nullable(),
	created_at: z.string().optional(),
	email: z.string(),
	full_name: z.string().optional().nullable(),
	id: z.string(),
	last_seen_at: z.string().optional().nullable(),
	updated_at: z.string().optional(),
});

export const publicProfilesUpdateSchema = z.object({
	avatar_url: z.string().optional().nullable(),
	created_at: z.string().optional(),
	email: z.string().optional(),
	full_name: z.string().optional().nullable(),
	id: z.string().optional(),
	last_seen_at: z.string().optional().nullable(),
	updated_at: z.string().optional(),
});

export const publicProjectTagsRowSchema = z.object({
	created_at: z.string(),
	project_id: z.string(),
	tag_id: z.string(),
});

export const publicProjectTagsInsertSchema = z.object({
	created_at: z.string().optional(),
	project_id: z.string(),
	tag_id: z.string(),
});

export const publicProjectTagsUpdateSchema = z.object({
	created_at: z.string().optional(),
	project_id: z.string().optional(),
	tag_id: z.string().optional(),
});

export const publicProjectTagsRelationshipsSchema = z.tuple([
	z.object({
		foreignKeyName: z.literal("project_tags_project_id_fkey"),
		columns: z.tuple([z.literal("project_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("projects"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("project_tags_project_id_fkey"),
		columns: z.tuple([z.literal("project_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("projects_with_tags"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("project_tags_tag_id_fkey"),
		columns: z.tuple([z.literal("tag_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("tag_statistics"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("project_tags_tag_id_fkey"),
		columns: z.tuple([z.literal("tag_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("tags"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
]);

export const publicProjectsRowSchema = z.object({
	created_at: z.string().nullable(),
	description: z.string().nullable(),
	id: z.string(),
	name: z.string(),
	status: z.string(),
	updated_at: z.string().nullable(),
	user_id: z.string().nullable(),
});

export const publicProjectsInsertSchema = z.object({
	created_at: z.string().optional().nullable(),
	description: z.string().optional().nullable(),
	id: z.string().optional(),
	name: z.string(),
	status: z.string().optional(),
	updated_at: z.string().optional().nullable(),
	user_id: z.string().optional().nullable(),
});

export const publicProjectsUpdateSchema = z.object({
	created_at: z.string().optional().nullable(),
	description: z.string().optional().nullable(),
	id: z.string().optional(),
	name: z.string().optional(),
	status: z.string().optional(),
	updated_at: z.string().optional().nullable(),
	user_id: z.string().optional().nullable(),
});

export const publicSharedLinksRowSchema = z.object({
	access_level: z.string(),
	created_at: z.string(),
	created_by: z.string(),
	description: z.string().nullable(),
	entity_id: z.string(),
	entity_type: z.string(),
	expires_at: z.string().nullable(),
	id: z.string(),
	is_active: z.boolean().nullable(),
	last_accessed_at: z.string().nullable(),
	never_expires: z.boolean().nullable(),
	password_hash: z.string().nullable(),
	requires_password: z.boolean().nullable(),
	token: z.string(),
	updated_at: z.string(),
	view_count: z.number().nullable(),
});

export const publicSharedLinksInsertSchema = z.object({
	access_level: z.string().optional(),
	created_at: z.string().optional(),
	created_by: z.string(),
	description: z.string().optional().nullable(),
	entity_id: z.string(),
	entity_type: z.string(),
	expires_at: z.string().optional().nullable(),
	id: z.string().optional(),
	is_active: z.boolean().optional().nullable(),
	last_accessed_at: z.string().optional().nullable(),
	never_expires: z.boolean().optional().nullable(),
	password_hash: z.string().optional().nullable(),
	requires_password: z.boolean().optional().nullable(),
	token: z.string(),
	updated_at: z.string().optional(),
	view_count: z.number().optional().nullable(),
});

export const publicSharedLinksUpdateSchema = z.object({
	access_level: z.string().optional(),
	created_at: z.string().optional(),
	created_by: z.string().optional(),
	description: z.string().optional().nullable(),
	entity_id: z.string().optional(),
	entity_type: z.string().optional(),
	expires_at: z.string().optional().nullable(),
	id: z.string().optional(),
	is_active: z.boolean().optional().nullable(),
	last_accessed_at: z.string().optional().nullable(),
	never_expires: z.boolean().optional().nullable(),
	password_hash: z.string().optional().nullable(),
	requires_password: z.boolean().optional().nullable(),
	token: z.string().optional(),
	updated_at: z.string().optional(),
	view_count: z.number().optional().nullable(),
});

export const publicTagsRowSchema = z.object({
	color: z.string(),
	created_at: z.string(),
	description: z.string().nullable(),
	icon: z.string().nullable(),
	id: z.string(),
	name: z.string(),
	slug: z.string(),
	updated_at: z.string(),
	usage_count: z.number().nullable(),
});

export const publicTagsInsertSchema = z.object({
	color: z.string().optional(),
	created_at: z.string().optional(),
	description: z.string().optional().nullable(),
	icon: z.string().optional().nullable(),
	id: z.string().optional(),
	name: z.string(),
	slug: z.string(),
	updated_at: z.string().optional(),
	usage_count: z.number().optional().nullable(),
});

export const publicTagsUpdateSchema = z.object({
	color: z.string().optional(),
	created_at: z.string().optional(),
	description: z.string().optional().nullable(),
	icon: z.string().optional().nullable(),
	id: z.string().optional(),
	name: z.string().optional(),
	slug: z.string().optional(),
	updated_at: z.string().optional(),
	usage_count: z.number().optional().nullable(),
});

export const publicTaskTagsRowSchema = z.object({
	created_at: z.string(),
	tag_id: z.string(),
	task_id: z.string(),
});

export const publicTaskTagsInsertSchema = z.object({
	created_at: z.string().optional(),
	tag_id: z.string(),
	task_id: z.string(),
});

export const publicTaskTagsUpdateSchema = z.object({
	created_at: z.string().optional(),
	tag_id: z.string().optional(),
	task_id: z.string().optional(),
});

export const publicTaskTagsRelationshipsSchema = z.tuple([
	z.object({
		foreignKeyName: z.literal("task_tags_tag_id_fkey"),
		columns: z.tuple([z.literal("tag_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("tag_statistics"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("task_tags_tag_id_fkey"),
		columns: z.tuple([z.literal("tag_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("tags"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("task_tags_task_id_fkey"),
		columns: z.tuple([z.literal("task_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("tasks"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("task_tags_task_id_fkey"),
		columns: z.tuple([z.literal("task_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("tasks_with_tags"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
]);

export const publicTasksRowSchema = z.object({
	created_at: z.string().nullable(),
	description: z.string().nullable(),
	due_date: z.string().nullable(),
	id: z.string(),
	priority: z.string().nullable(),
	project_id: z.string().nullable(),
	status: z.string(),
	title: z.string(),
	updated_at: z.string().nullable(),
	user_id: z.string().nullable(),
});

export const publicTasksInsertSchema = z.object({
	created_at: z.string().optional().nullable(),
	description: z.string().optional().nullable(),
	due_date: z.string().optional().nullable(),
	id: z.string().optional(),
	priority: z.string().optional().nullable(),
	project_id: z.string().optional().nullable(),
	status: z.string().optional(),
	title: z.string(),
	updated_at: z.string().optional().nullable(),
	user_id: z.string().optional().nullable(),
});

export const publicTasksUpdateSchema = z.object({
	created_at: z.string().optional().nullable(),
	description: z.string().optional().nullable(),
	due_date: z.string().optional().nullable(),
	id: z.string().optional(),
	priority: z.string().optional().nullable(),
	project_id: z.string().optional().nullable(),
	status: z.string().optional(),
	title: z.string().optional(),
	updated_at: z.string().optional().nullable(),
	user_id: z.string().optional().nullable(),
});

export const publicTasksRelationshipsSchema = z.tuple([
	z.object({
		foreignKeyName: z.literal("tasks_project_id_fkey"),
		columns: z.tuple([z.literal("project_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("projects"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("tasks_project_id_fkey"),
		columns: z.tuple([z.literal("project_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("projects_with_tags"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
]);

export const publicTestNotesRowSchema = z.object({
	created_at: z.string(),
	description: z.string().nullable(),
	id: z.string(),
	title: z.string().nullable(),
	updated_at: z.string(),
	user_id: z.string().nullable(),
});

export const publicTestNotesInsertSchema = z.object({
	created_at: z.string().optional(),
	description: z.string().optional().nullable(),
	id: z.string(),
	title: z.string().optional().nullable(),
	updated_at: z.string().optional(),
	user_id: z.string().optional().nullable(),
});

export const publicTestNotesUpdateSchema = z.object({
	created_at: z.string().optional(),
	description: z.string().optional().nullable(),
	id: z.string().optional(),
	title: z.string().optional().nullable(),
	updated_at: z.string().optional(),
	user_id: z.string().optional().nullable(),
});

export const publicFilesWithEntitiesRowSchema = z.object({
	bucket: z.string().nullable(),
	can_delete: z.boolean().nullable(),
	can_index: z.boolean().nullable(),
	can_read: z.boolean().nullable(),
	can_write: z.boolean().nullable(),
	chunks_count: z.number().nullable(),
	created_at: z.string().nullable(),
	created_by: z.string().nullable(),
	embedding_model: z.string().nullable(),
	entities: jsonSchema.nullable(),
	id: z.string().nullable(),
	index_status: z.string().nullable(),
	indexing_error: z.string().nullable(),
	indexing_progress: z.number().nullable(),
	is_folder: z.boolean().nullable(),
	last_indexed: z.string().nullable(),
	mime_type: z.string().nullable(),
	name: z.string().nullable(),
	parent_id: z.string().nullable(),
	path: z.string().nullable(),
	size: z.number().nullable(),
	sort_order: z.number().nullable(),
	starred: z.boolean().nullable(),
	storage_path: z.string().nullable(),
	storage_provider: z.string().nullable(),
	tags: z.array(z.string()).nullable(),
	type: z.string().nullable(),
	updated_at: z.string().nullable(),
	updated_by: z.string().nullable(),
	vector_id: z.string().nullable(),
});

export const publicFilesWithEntitiesRelationshipsSchema = z.tuple([
	z.object({
		foreignKeyName: z.literal("files_parent_id_fkey"),
		columns: z.tuple([z.literal("parent_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("files_parent_id_fkey"),
		columns: z.tuple([z.literal("parent_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files_with_entities"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("files_parent_id_fkey"),
		columns: z.tuple([z.literal("parent_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files_with_item_count"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
]);

export const publicFilesWithItemCountRowSchema = z.object({
	bucket: z.string().nullable(),
	can_delete: z.boolean().nullable(),
	can_index: z.boolean().nullable(),
	can_read: z.boolean().nullable(),
	can_write: z.boolean().nullable(),
	chunks_count: z.number().nullable(),
	created_at: z.string().nullable(),
	created_by: z.string().nullable(),
	embedding_model: z.string().nullable(),
	id: z.string().nullable(),
	index_status: z.string().nullable(),
	indexing_error: z.string().nullable(),
	indexing_progress: z.number().nullable(),
	is_folder: z.boolean().nullable(),
	item_count: z.number().nullable(),
	last_indexed: z.string().nullable(),
	mime_type: z.string().nullable(),
	name: z.string().nullable(),
	parent_id: z.string().nullable(),
	path: z.string().nullable(),
	size: z.number().nullable(),
	sort_order: z.number().nullable(),
	starred: z.boolean().nullable(),
	storage_path: z.string().nullable(),
	storage_provider: z.string().nullable(),
	tags: z.array(z.string()).nullable(),
	type: z.string().nullable(),
	updated_at: z.string().nullable(),
	updated_by: z.string().nullable(),
	vector_id: z.string().nullable(),
});

export const publicFilesWithItemCountInsertSchema = z.object({
	bucket: z.string().optional().nullable(),
	can_delete: z.boolean().optional().nullable(),
	can_index: z.boolean().optional().nullable(),
	can_read: z.boolean().optional().nullable(),
	can_write: z.boolean().optional().nullable(),
	chunks_count: z.number().optional().nullable(),
	created_at: z.string().optional().nullable(),
	created_by: z.string().optional().nullable(),
	embedding_model: z.string().optional().nullable(),
	id: z.string().optional().nullable(),
	index_status: z.string().optional().nullable(),
	indexing_error: z.string().optional().nullable(),
	indexing_progress: z.number().optional().nullable(),
	is_folder: z.boolean().optional().nullable(),
	item_count: z.never().optional(),
	last_indexed: z.string().optional().nullable(),
	mime_type: z.string().optional().nullable(),
	name: z.string().optional().nullable(),
	parent_id: z.string().optional().nullable(),
	path: z.string().optional().nullable(),
	size: z.number().optional().nullable(),
	sort_order: z.number().optional().nullable(),
	starred: z.boolean().optional().nullable(),
	storage_path: z.string().optional().nullable(),
	storage_provider: z.string().optional().nullable(),
	tags: z.array(z.string()).optional().nullable(),
	type: z.string().optional().nullable(),
	updated_at: z.string().optional().nullable(),
	updated_by: z.string().optional().nullable(),
	vector_id: z.string().optional().nullable(),
});

export const publicFilesWithItemCountUpdateSchema = z.object({
	bucket: z.string().optional().nullable(),
	can_delete: z.boolean().optional().nullable(),
	can_index: z.boolean().optional().nullable(),
	can_read: z.boolean().optional().nullable(),
	can_write: z.boolean().optional().nullable(),
	chunks_count: z.number().optional().nullable(),
	created_at: z.string().optional().nullable(),
	created_by: z.string().optional().nullable(),
	embedding_model: z.string().optional().nullable(),
	id: z.string().optional().nullable(),
	index_status: z.string().optional().nullable(),
	indexing_error: z.string().optional().nullable(),
	indexing_progress: z.number().optional().nullable(),
	is_folder: z.boolean().optional().nullable(),
	item_count: z.never().optional(),
	last_indexed: z.string().optional().nullable(),
	mime_type: z.string().optional().nullable(),
	name: z.string().optional().nullable(),
	parent_id: z.string().optional().nullable(),
	path: z.string().optional().nullable(),
	size: z.number().optional().nullable(),
	sort_order: z.number().optional().nullable(),
	starred: z.boolean().optional().nullable(),
	storage_path: z.string().optional().nullable(),
	storage_provider: z.string().optional().nullable(),
	tags: z.array(z.string()).optional().nullable(),
	type: z.string().optional().nullable(),
	updated_at: z.string().optional().nullable(),
	updated_by: z.string().optional().nullable(),
	vector_id: z.string().optional().nullable(),
});

export const publicFilesWithItemCountRelationshipsSchema = z.tuple([
	z.object({
		foreignKeyName: z.literal("files_parent_id_fkey"),
		columns: z.tuple([z.literal("parent_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("files_parent_id_fkey"),
		columns: z.tuple([z.literal("parent_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files_with_entities"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("files_parent_id_fkey"),
		columns: z.tuple([z.literal("parent_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("files_with_item_count"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
]);

export const publicInviteStatisticsRowSchema = z.object({
	accepted_invites: z.number().nullable(),
	avg_acceptance_time_seconds: z.number().nullable(),
	expired_invites: z.number().nullable(),
	first_invite_date: z.string().nullable(),
	invited_by: z.string().nullable(),
	last_invite_date: z.string().nullable(),
	pending_invites: z.number().nullable(),
	revoked_invites: z.number().nullable(),
	total_invites: z.number().nullable(),
});

export const publicProjectsWithTagsRowSchema = z.object({
	created_at: z.string().nullable(),
	description: z.string().nullable(),
	id: z.string().nullable(),
	name: z.string().nullable(),
	status: z.string().nullable(),
	tags: jsonSchema.nullable(),
	updated_at: z.string().nullable(),
});

export const publicSharedLinkStatisticsRowSchema = z.object({
	active_links: z.number().nullable(),
	avg_views: z.number().nullable(),
	created_by: z.string().nullable(),
	entity_type: z.string().nullable(),
	expired_active_links: z.number().nullable(),
	max_views: z.number().nullable(),
	password_protected_links: z.number().nullable(),
	total_links: z.number().nullable(),
	total_views: z.number().nullable(),
	valid_links: z.number().nullable(),
});

export const publicTagStatisticsRowSchema = z.object({
	color: z.string().nullable(),
	created_at: z.string().nullable(),
	description: z.string().nullable(),
	icon: z.string().nullable(),
	id: z.string().nullable(),
	name: z.string().nullable(),
	project_count: z.number().nullable(),
	slug: z.string().nullable(),
	task_count: z.number().nullable(),
	updated_at: z.string().nullable(),
	usage_count: z.number().nullable(),
});

export const publicTasksWithTagsRowSchema = z.object({
	created_at: z.string().nullable(),
	description: z.string().nullable(),
	due_date: z.string().nullable(),
	id: z.string().nullable(),
	priority: z.string().nullable(),
	project_id: z.string().nullable(),
	status: z.string().nullable(),
	tags: jsonSchema.nullable(),
	title: z.string().nullable(),
	updated_at: z.string().nullable(),
});

export const publicTasksWithTagsRelationshipsSchema = z.tuple([
	z.object({
		foreignKeyName: z.literal("tasks_project_id_fkey"),
		columns: z.tuple([z.literal("project_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("projects"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
	z.object({
		foreignKeyName: z.literal("tasks_project_id_fkey"),
		columns: z.tuple([z.literal("project_id")]),
		isOneToOne: z.literal(false),
		referencedRelation: z.literal("projects_with_tags"),
		referencedColumns: z.tuple([z.literal("id")]),
	}),
]);

export const publicAcceptInviteArgsSchema = z.object({
	invite_token: z.string(),
	user_id: z.string(),
});

export const publicAcceptInviteReturnsSchema = z.boolean();

export const publicCanUserShareEntityArgsSchema = z.object({
	p_entity_id: z.string(),
	p_entity_type: z.string(),
	p_user_id: z.string(),
});

export const publicCanUserShareEntityReturnsSchema = z.boolean();

export const publicCleanupExpiredSharedLinksArgsSchema = z.never();

export const publicCleanupExpiredSharedLinksReturnsSchema = z.array(
	z.object({
		deactivated_count: z.number(),
		deleted_count: z.number(),
	}),
);

export const publicCountFolderItemsArgsSchema = z.object({
	folder_id: z.string(),
});

export const publicCountFolderItemsReturnsSchema = z.number();

export const publicGenerateInviteTokenArgsSchema = z.never();

export const publicGenerateInviteTokenReturnsSchema = z.string();

export const publicGenerateShareTokenArgsSchema = z.never();

export const publicGenerateShareTokenReturnsSchema = z.string();

export const publicGetActiveInvitesArgsSchema = z.object({
	user_id: z.string(),
});

export const publicGetActiveInvitesReturnsSchema = z.array(
	z.object({
		created_at: z.string(),
		days_until_expiry: z.number(),
		email: z.string(),
		expires_at: z.string(),
		id: z.string(),
		role: z.string(),
		status: z.string(),
		token: z.string(),
	}),
);

export const publicGetShareStatusArgsSchema = z.object({
	link_token: z.string(),
});

export const publicGetShareStatusReturnsSchema = z.array(
	z.object({
		access_level: z.string(),
		created_at: z.string(),
		description: z.string(),
		entity_id: z.string(),
		entity_type: z.string(),
		error_message: z.string(),
		expires_at: z.string(),
		is_valid: z.boolean(),
		last_accessed_at: z.string(),
		never_expires: z.boolean(),
		requires_password: z.boolean(),
		view_count: z.number(),
	}),
);

export const publicGetSharedEntityArgsSchema = z.object({
	link_token: z.string(),
});

export const publicGetSharedEntityReturnsSchema = z.array(
	z.object({
		access_level: z.string(),
		entity_data: jsonSchema,
		entity_id: z.string(),
		entity_type: z.string(),
		error_message: z.string(),
		expires_at: z.string(),
		is_valid: z.boolean(),
		requires_password: z.boolean(),
		view_count: z.number(),
	}),
);

export const publicIncrementShareViewCountArgsSchema = z.object({
	link_token: z.string(),
});

export const publicIncrementShareViewCountReturnsSchema = z.undefined();

export const publicIsInviteValidArgsSchema = z.object({
	invite_token: z.string(),
});

export const publicIsInviteValidReturnsSchema = z.boolean();

export const publicIsSharedLinkValidArgsSchema = z.object({
	link_token: z.string(),
});

export const publicIsSharedLinkValidReturnsSchema = z.boolean();

export const publicVerifySharePasswordArgsSchema = z.object({
	link_token: z.string(),
	password: z.string(),
});

export const publicVerifySharePasswordReturnsSchema = z.boolean();

export type Json = z.infer<typeof jsonSchema>;
export type PublicAirCompaniesRow = z.infer<typeof publicAirCompaniesRowSchema>;
export type PublicAirCompaniesInsert = z.infer<
	typeof publicAirCompaniesInsertSchema
>;
export type PublicAirCompaniesUpdate = z.infer<
	typeof publicAirCompaniesUpdateSchema
>;
export type PublicAirDepartmentsRow = z.infer<
	typeof publicAirDepartmentsRowSchema
>;
export type PublicAirDepartmentsInsert = z.infer<
	typeof publicAirDepartmentsInsertSchema
>;
export type PublicAirDepartmentsUpdate = z.infer<
	typeof publicAirDepartmentsUpdateSchema
>;
export type PublicAirDocumentTemplatesRow = z.infer<
	typeof publicAirDocumentTemplatesRowSchema
>;
export type PublicAirDocumentTemplatesInsert = z.infer<
	typeof publicAirDocumentTemplatesInsertSchema
>;
export type PublicAirDocumentTemplatesUpdate = z.infer<
	typeof publicAirDocumentTemplatesUpdateSchema
>;
export type PublicAirDocumentsRow = z.infer<typeof publicAirDocumentsRowSchema>;
export type PublicAirDocumentsInsert = z.infer<
	typeof publicAirDocumentsInsertSchema
>;
export type PublicAirDocumentsUpdate = z.infer<
	typeof publicAirDocumentsUpdateSchema
>;
export type PublicAirDocumentsRelationships = z.infer<
	typeof publicAirDocumentsRelationshipsSchema
>;
export type PublicAirFavoritesRow = z.infer<typeof publicAirFavoritesRowSchema>;
export type PublicAirFavoritesInsert = z.infer<
	typeof publicAirFavoritesInsertSchema
>;
export type PublicAirFavoritesUpdate = z.infer<
	typeof publicAirFavoritesUpdateSchema
>;
export type PublicAirGeneratedDocumentsRow = z.infer<
	typeof publicAirGeneratedDocumentsRowSchema
>;
export type PublicAirGeneratedDocumentsInsert = z.infer<
	typeof publicAirGeneratedDocumentsInsertSchema
>;
export type PublicAirGeneratedDocumentsUpdate = z.infer<
	typeof publicAirGeneratedDocumentsUpdateSchema
>;
export type PublicAirProfilesRow = z.infer<typeof publicAirProfilesRowSchema>;
export type PublicAirProfilesInsert = z.infer<
	typeof publicAirProfilesInsertSchema
>;
export type PublicAirProfilesUpdate = z.infer<
	typeof publicAirProfilesUpdateSchema
>;
export type PublicAirProfilesRelationships = z.infer<
	typeof publicAirProfilesRelationshipsSchema
>;
export type PublicAirRolePromptsRow = z.infer<
	typeof publicAirRolePromptsRowSchema
>;
export type PublicAirRolePromptsInsert = z.infer<
	typeof publicAirRolePromptsInsertSchema
>;
export type PublicAirRolePromptsUpdate = z.infer<
	typeof publicAirRolePromptsUpdateSchema
>;
export type PublicFileEntityLinksRow = z.infer<
	typeof publicFileEntityLinksRowSchema
>;
export type PublicFileEntityLinksInsert = z.infer<
	typeof publicFileEntityLinksInsertSchema
>;
export type PublicFileEntityLinksUpdate = z.infer<
	typeof publicFileEntityLinksUpdateSchema
>;
export type PublicFileEntityLinksRelationships = z.infer<
	typeof publicFileEntityLinksRelationshipsSchema
>;
export type PublicFileVersionsRow = z.infer<typeof publicFileVersionsRowSchema>;
export type PublicFileVersionsInsert = z.infer<
	typeof publicFileVersionsInsertSchema
>;
export type PublicFileVersionsUpdate = z.infer<
	typeof publicFileVersionsUpdateSchema
>;
export type PublicFileVersionsRelationships = z.infer<
	typeof publicFileVersionsRelationshipsSchema
>;
export type PublicFilesRow = z.infer<typeof publicFilesRowSchema>;
export type PublicFilesInsert = z.infer<typeof publicFilesInsertSchema>;
export type PublicFilesUpdate = z.infer<typeof publicFilesUpdateSchema>;
export type PublicFilesRelationships = z.infer<
	typeof publicFilesRelationshipsSchema
>;
export type PublicInvitesRow = z.infer<typeof publicInvitesRowSchema>;
export type PublicInvitesInsert = z.infer<typeof publicInvitesInsertSchema>;
export type PublicInvitesUpdate = z.infer<typeof publicInvitesUpdateSchema>;
export type PublicProfilesRow = z.infer<typeof publicProfilesRowSchema>;
export type PublicProfilesInsert = z.infer<typeof publicProfilesInsertSchema>;
export type PublicProfilesUpdate = z.infer<typeof publicProfilesUpdateSchema>;
export type PublicProjectTagsRow = z.infer<typeof publicProjectTagsRowSchema>;
export type PublicProjectTagsInsert = z.infer<
	typeof publicProjectTagsInsertSchema
>;
export type PublicProjectTagsUpdate = z.infer<
	typeof publicProjectTagsUpdateSchema
>;
export type PublicProjectTagsRelationships = z.infer<
	typeof publicProjectTagsRelationshipsSchema
>;
export type PublicProjectsRow = z.infer<typeof publicProjectsRowSchema>;
export type PublicProjectsInsert = z.infer<typeof publicProjectsInsertSchema>;
export type PublicProjectsUpdate = z.infer<typeof publicProjectsUpdateSchema>;
export type PublicSharedLinksRow = z.infer<typeof publicSharedLinksRowSchema>;
export type PublicSharedLinksInsert = z.infer<
	typeof publicSharedLinksInsertSchema
>;
export type PublicSharedLinksUpdate = z.infer<
	typeof publicSharedLinksUpdateSchema
>;
export type PublicTagsRow = z.infer<typeof publicTagsRowSchema>;
export type PublicTagsInsert = z.infer<typeof publicTagsInsertSchema>;
export type PublicTagsUpdate = z.infer<typeof publicTagsUpdateSchema>;
export type PublicTaskTagsRow = z.infer<typeof publicTaskTagsRowSchema>;
export type PublicTaskTagsInsert = z.infer<typeof publicTaskTagsInsertSchema>;
export type PublicTaskTagsUpdate = z.infer<typeof publicTaskTagsUpdateSchema>;
export type PublicTaskTagsRelationships = z.infer<
	typeof publicTaskTagsRelationshipsSchema
>;
export type PublicTasksRow = z.infer<typeof publicTasksRowSchema>;
export type PublicTasksInsert = z.infer<typeof publicTasksInsertSchema>;
export type PublicTasksUpdate = z.infer<typeof publicTasksUpdateSchema>;
export type PublicTasksRelationships = z.infer<
	typeof publicTasksRelationshipsSchema
>;
export type PublicTestNotesRow = z.infer<typeof publicTestNotesRowSchema>;
export type PublicTestNotesInsert = z.infer<typeof publicTestNotesInsertSchema>;
export type PublicTestNotesUpdate = z.infer<typeof publicTestNotesUpdateSchema>;
export type PublicFilesWithEntitiesRow = z.infer<
	typeof publicFilesWithEntitiesRowSchema
>;
export type PublicFilesWithEntitiesRelationships = z.infer<
	typeof publicFilesWithEntitiesRelationshipsSchema
>;
export type PublicFilesWithItemCountRow = z.infer<
	typeof publicFilesWithItemCountRowSchema
>;
export type PublicFilesWithItemCountInsert = z.infer<
	typeof publicFilesWithItemCountInsertSchema
>;
export type PublicFilesWithItemCountUpdate = z.infer<
	typeof publicFilesWithItemCountUpdateSchema
>;
export type PublicFilesWithItemCountRelationships = z.infer<
	typeof publicFilesWithItemCountRelationshipsSchema
>;
export type PublicInviteStatisticsRow = z.infer<
	typeof publicInviteStatisticsRowSchema
>;
export type PublicProjectsWithTagsRow = z.infer<
	typeof publicProjectsWithTagsRowSchema
>;
export type PublicSharedLinkStatisticsRow = z.infer<
	typeof publicSharedLinkStatisticsRowSchema
>;
export type PublicTagStatisticsRow = z.infer<
	typeof publicTagStatisticsRowSchema
>;
export type PublicTasksWithTagsRow = z.infer<
	typeof publicTasksWithTagsRowSchema
>;
export type PublicTasksWithTagsRelationships = z.infer<
	typeof publicTasksWithTagsRelationshipsSchema
>;
export type PublicAcceptInviteArgs = z.infer<
	typeof publicAcceptInviteArgsSchema
>;
export type PublicAcceptInviteReturns = z.infer<
	typeof publicAcceptInviteReturnsSchema
>;
export type PublicCanUserShareEntityArgs = z.infer<
	typeof publicCanUserShareEntityArgsSchema
>;
export type PublicCanUserShareEntityReturns = z.infer<
	typeof publicCanUserShareEntityReturnsSchema
>;
export type PublicCleanupExpiredSharedLinksArgs = z.infer<
	typeof publicCleanupExpiredSharedLinksArgsSchema
>;
export type PublicCleanupExpiredSharedLinksReturns = z.infer<
	typeof publicCleanupExpiredSharedLinksReturnsSchema
>;
export type PublicCountFolderItemsArgs = z.infer<
	typeof publicCountFolderItemsArgsSchema
>;
export type PublicCountFolderItemsReturns = z.infer<
	typeof publicCountFolderItemsReturnsSchema
>;
export type PublicGenerateInviteTokenArgs = z.infer<
	typeof publicGenerateInviteTokenArgsSchema
>;
export type PublicGenerateInviteTokenReturns = z.infer<
	typeof publicGenerateInviteTokenReturnsSchema
>;
export type PublicGenerateShareTokenArgs = z.infer<
	typeof publicGenerateShareTokenArgsSchema
>;
export type PublicGenerateShareTokenReturns = z.infer<
	typeof publicGenerateShareTokenReturnsSchema
>;
export type PublicGetActiveInvitesArgs = z.infer<
	typeof publicGetActiveInvitesArgsSchema
>;
export type PublicGetActiveInvitesReturns = z.infer<
	typeof publicGetActiveInvitesReturnsSchema
>;
export type PublicGetShareStatusArgs = z.infer<
	typeof publicGetShareStatusArgsSchema
>;
export type PublicGetShareStatusReturns = z.infer<
	typeof publicGetShareStatusReturnsSchema
>;
export type PublicGetSharedEntityArgs = z.infer<
	typeof publicGetSharedEntityArgsSchema
>;
export type PublicGetSharedEntityReturns = z.infer<
	typeof publicGetSharedEntityReturnsSchema
>;
export type PublicIncrementShareViewCountArgs = z.infer<
	typeof publicIncrementShareViewCountArgsSchema
>;
export type PublicIncrementShareViewCountReturns = z.infer<
	typeof publicIncrementShareViewCountReturnsSchema
>;
export type PublicIsInviteValidArgs = z.infer<
	typeof publicIsInviteValidArgsSchema
>;
export type PublicIsInviteValidReturns = z.infer<
	typeof publicIsInviteValidReturnsSchema
>;
export type PublicIsSharedLinkValidArgs = z.infer<
	typeof publicIsSharedLinkValidArgsSchema
>;
export type PublicIsSharedLinkValidReturns = z.infer<
	typeof publicIsSharedLinkValidReturnsSchema
>;
export type PublicVerifySharePasswordArgs = z.infer<
	typeof publicVerifySharePasswordArgsSchema
>;
export type PublicVerifySharePasswordReturns = z.infer<
	typeof publicVerifySharePasswordReturnsSchema
>;
